### ISSUE TITLE
No response when clicking "Play it"

### ISSUE THREAD

**Issue by SunXingZhe-WJ** [asukaminato0721/mmaplayer#11]
I had wolframscript and WolframPlayer by Wolfram Engine, and added the folder into PATH, but it just does not respond when I click "play it".
Do I need some more configuration?

**Comment by asukaminato0721** [comment]
I find the problem, 

```mma
WaitAsynchronousTask::asyncinv: Argument ZeroMQLink`Private`$AsyncState[Task] is not a valid AsynchronousTask object.
Exiting...
```

**Comment by asukaminato0721** [comment]
check https://github.com/asukaminato0721/mmaplayer/releases/tag/0.0.4

**Comment by SunXingZhe-WJ** [comment]
It works! A big thank you!

**Comment by asukaminato0721** [comment]
https://github.com/arnoudbuzing/wolfram-server/issues/6 find it here
